# Generated by Django 3.1.6 on 2021-03-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default=1, upload_to='user_pics'),
            preserve_default=False,
        ),
    ]
