# Generated by Django 3.1.6 on 2021-03-23 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_intltransferrequest_localtransferrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intltransferrequest',
            options={'verbose_name': 'International Transfer Request', 'verbose_name_plural': 'International Transfer Requests'},
        ),
        migrations.AlterModelOptions(
            name='localtransferrequest',
            options={'verbose_name': 'Local Transfer Request', 'verbose_name_plural': 'Local Transfer Requests'},
        ),
        migrations.AlterModelOptions(
            name='userbankaccount',
            options={'verbose_name': 'Bank Account', 'verbose_name_plural': 'Bank Accounts'},
        ),
    ]
