# Generated by Django 3.1.6 on 2021-03-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_withdrawalhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawalhistory',
            options={'verbose_name_plural': 'Histories'},
        ),
        migrations.RemoveField(
            model_name='withdrawalhistory',
            name='paid',
        ),
        migrations.AddField(
            model_name='withdrawalhistory',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Successful', 'Successful')], default='ssh', max_length=25),
            preserve_default=False,
        ),
    ]
